### ISSUE TITLE
Login browser appears again after successfully login on Xamarin Forms (Android)

### ISSUE THREAD

**Issue by juniorsaraviao** [auth0/auth0-oidc-client-net#242] opened 2023-02-07 03:59 UTC
# Issue Report

### Description

I found an issue and posted it on the [Auth0 community](https://community.auth0.com/t/login-browser-stays-open-after-successfully-login-on-android/89050). Also, I created a bug report in [Auth0 Xamarin Sample](https://github.com/auth0-samples/auth0-xamarin-oidc-samples/issues/47)

When the login is successful and the app is closed using the **Phone back button**, the login browser appears again (Auth0.OidcClient.AndroidX v3.2.6).

### Expected behaviour

Close the login browser so that when pressing the Phone back button, the browser doesn't appear again.

### Actual behaviour 

The login browser appears again after pressing the Phone back button.

### Steps to reproduce the problem

1. Use the Auth0 Xamarin sample [here](https://github.com/auth0-samples/auth0-xamarin-oidc-samples/tree/master/Samples/Forms_NS/FormsSample) or create a project following these [steps](https://github.com/auth0-samples/auth0-xamarin-oidc-samples/tree/master/Samples/Forms_NS#getting-started).
2. Log in with valid credentials.
3. Press the phone back button on the bottom.
4. The login browser appears again.

### Language / Framework Versions

1. **Language used:** C#
2. **Framework used:** Xamarin forms (v5.0.0.2515)

### Testing environment

1. **Operating system:** Windows 10
2. **Browser version:** Samsung A11 (Android 11) - Genymotion Custom Phone (Android 8)

**Comment by frederikprijck** [comment] 2023-02-07 08:33
Thanks for reporting, sorry for missing the report on the Sample repository. I will look into this and see what could be causing it and how we can solve it.

**Comment by frederikprijck** [comment] 2023-02-07 13:44
I opened a PR which I believe should address it. I have been able to, partly, reproduce it, and resolve it using that change.

Before being able to merge it, I will need to verify if it works in Xamarin Forms. But currently having some issues with my Windows machine.

Any chance you could also give that PR a try?

**Comment by juniorsaraviao** [comment] 2023-02-14 13:30
Hi @frederikprijck, just a question when could we have a new version that includes this change?

**Comment by frederikprijck** [comment] 2023-02-14 13:31
I am currently working on another fix for this SDK, then I plan to cut a release. I would say somewhere this week.

**Comment by frederikprijck** [comment] 2023-02-14 16:07
The release is out. Let me know if it would still not work!

**Comment by juniorsaraviao** [comment] 2023-02-14 20:16
I just checked the new release version and the browser doesn't appear after pressing the back button.
However, I saw the browser was still in the background if I pressed the overview button. Let me know if I should open a new issue for that

![image](https://user-images.githubusercontent.com/43689290/218851932-d597412d-88ca-4c52-b4ad-89f3f10375f6.png)

**Comment by frederikprijck** [comment] 2023-02-14 20:52
Thanks, I will take another look to see how we can fix that.

**Comment by frederikprijck** [comment] 2023-02-14 21:43
Any chance you can try out using your own browser as below? I am still having difficulties running Xamarin Forms and can not reproduce the behavior outside of Xamarin Forms.

```charp
    public class MyChromeCustomTabsBrowser : AndroidBrowserBase
    {
        /// <summary>
        /// Create a new instance of <see cref="MyChromeCustomTabsBrowser"/> for a given <see cref="Context"/>.
        /// </summary>
        /// <param name="context"><see cref="Context"/> provided to any subsequent callback.</param>
        public MyChromeCustomTabsBrowser(Context context = null)
            : base(context)
        {
        }

        /// <inheritdoc/>
        protected override void OpenBrowser(Android.Net.Uri uri, Context context = null)
        {
            using (var builder = new CustomTabsIntent.Builder())
            using (var customTabsIntent = builder.Build())
            {
                if (IsNewTask)
                    customTabsIntent.Intent.AddFlags(ActivityFlags.NewTask | ActivityFlags.NoHistory | ActivityFlags.ClearTask);
                customTabsIntent.LaunchUrl(context, uri);
            }
        }
    }
```

Then pass this one as Browser when creating the Auth0Client instance. 

```csharp
new Auth0Client(new Auth0ClientOptions
{
    Browser = new MyChromeCustomTabsBrowser();
});
```

I will continue to try and fix running Xamarin.Forms, but might be good if you could give this a try to avoid cutting a release that might still not do what you want for your use-case.

**Comment by juniorsaraviao** [comment] 2023-02-14 22:40
I used the code above but the browser stayed in the background.

**Comment by frederikprijck** [comment] 2023-03-14 11:26
I have been unable to reproduce the last behavior you mentioned [here](https://github.com/auth0/auth0-oidc-client-net/issues/242#issuecomment-1430320288) using [the sample you mentioned](https://github.com/auth0-samples/auth0-xamarin-oidc-samples/tree/master/Samples/Forms_NS/FormsSample) as well.

**Comment by juniorsaraviao** [comment] 2023-03-14 14:53
I used the Genymotion Custom Phone Android v10 (emulator) and I saw the behavior described [here](https://github.com/auth0/auth0-oidc-client-net/issues/242#issuecomment-1430320288). I'm not sure if this issue could be related to the Android OS

**Comment by frederikprijck** [comment] 2023-03-14 15:15
I'm going to close this, happy to reopen if this would come up with other devices, but I can't reproduce it using a couple of different emulators and devices.

**Closed by frederikprijck** 2023-03-14 15:15 UTC
