### ISSUE TITLE
Auth0.OidcClient assembly doesn't have a strong name.

### ISSUE THREAD

**Issue by nataliahering** [auth0/auth0-oidc-client-net#187] opened 2021-04-06 10:29 UTC
### Describe the problem

The Auth0.OidcClient assembly doesn't seem to have a strong name.

### What was the expected behavior?

To already have a strong name.

### Reproduction

Open a .NET Framework project, which expects assemblies to be signed.

In a C# class add a reference:
```using Auth0.OidcClient;```

compile the project and this error is thrown
```Error CS8002	Referenced assembly 'Auth0.OidcClient, Version=3.1.2.0, Culture=neutral,PublicKeyToken=null' does not have a strong name.```

### Environment

- **Version of this library used:** Auth0.OidcClient.Core, v3.1.2.0
- **Which framework are you using, if applicable:** .NET framework

**Comment by frederikprijck** [comment] 2021-04-07 12:16
Thanks for reporting this! That sounds like a fair request and will look into making the assembly strongly named, Will add it into our internal backlog as well!

**Comment by frederikprijck** [comment] 2021-04-12 07:45
Hi @nataliahering,

Could you elaborate on which Nuget package you are using that is causing that error?

It looks like all of our OIDC Client SDKs are actually signed and have a strong name, except for our Android SDKs.

- I tried importing our SDKs in a project that is signed, and it doesn't show me any warnings (it does show me warnings when I try using another, unsigned, assembly).
- I also verified the DLLs on Nuget by using `sn.exe` (`sn -v C:\PATH\TO\Auth0.OidcClient.dll`)

![image](https://user-images.githubusercontent.com/2146903/114358879-b549f780-9b73-11eb-9c59-d884983fe22b.png)

Could also help if you could provide some detailed reproduction steps or a runnable sample that has the mentioned error.

Thanks!

**Comment by frederikprijck** [comment] 2021-05-05 07:03
As we didn't hear back from you, we are closing this issue.

Happy to re-open if you have some more feedback for us here.

**Closed by frederikprijck** 2021-05-05 07:03 UTC
Labels: waiting for customer
