### ISSUE TITLE
Android: tapping back button doesn't cause LoginAsync to return

### ISSUE THREAD

**Issue by jeremy-bridges** [auth0/auth0-oidc-client-net#181] opened 2021-02-24 00:09 UTC
### Description
The ActivityMediator.Instance.ActivityMessageReceived isn't being fired when the back button is tapped in the web browser that is opened when the login call is made.

### What was the expected behavior?
ActivityMediator.Instance.ActivityMessageReceived event fires, completing the TaskCompletionSource started in AndroidBrowserBase.

### Reproduction
Just use the OidcClient.LoginAsync under Android.

### Environment
Android, using Chrome or Firefox.

**Comment by frederikprijck** [comment] 2021-02-24 08:29
Hi,

I have been unable to reproduce this, here is a recording of what I am seeing: https://www.loom.com/share/ea4dee71f5d34707ac7c0b8819b3ee3c

I tried those both in an Emulator (Pixel 3 running Android 10) as well as on a physical device.

Could you provide a bit more information or, preferably, a reproduction?

**Comment by frederikprijck** [comment] 2021-03-08 10:36
Closing this as we haven't gotten any response.

If this continues to be an issue, we can reopen.

**Closed by frederikprijck** 2021-03-08 10:36 UTC

**Comment by jploo** [comment] 2021-03-08 21:48
For anyone else who is seeing this, make sure you call ActivityMediator.Instance.Cancel(); from your Activity's OnResume(...), otherwise the LoginAsync task will never complete if canceled. That was my issue, and probably Jeremy's issue as well.

**Comment by jeremy-bridges** [comment] 2021-03-11 19:35
Sorry for my lack of attention. The back button in question is not the hardware one. On a Galaxy S6 Lite, a back button shows up on the browser frame. Using ActivityMediator.Instance.Cancel() in OnResume did work for me in my case. Thank you jploo!
